Parameterize tests to cover more storage types
ibissource/ibis-ladybug pull request #87
Opened 2021-12-16 19:39 UTC by mhdirkse

2021-12-16 19:45 UTC, mhdirkse commented
At this point, test `testRerun[Memory storage]` fails. The report retrieved in line 99 has storage id 0. This makes the test fail, because a checkpoint level is also zero. The level zero is replaced by an IGNORE_* string for the ignored storage id.

2021-12-17 08:55 UTC, mhdirkse commented
The issue with line 99 has been fixed. The test still does not succeed.

2021-12-17 17:33 UTC, mhdirkse commented
All tests succeed now, so ready-for-review. I disabled two tests for in-memory storages because I found test logic that was specific to file storages. It is not trivial to make that logic storage-independant. I also added a few TODOs.

2022-01-04 15:38 UTC, jacodg requested changes

2022-01-04 15:38 UTC, jacodg commented on src/main/java/nl/nn/testtool/storage/memory/Storage.java
>  	protected String name;
Can we configure a high initial storageId for the unit tests only and leave the default to 0?

2022-01-05 11:42 UTC, jacodg approved these changes

2022-01-05 11:45 UTC, merged